# **Orientações **

*  Crie uma nova linha ao implementar as soluções para não apagar as respostas desejadas. 



1) Cria um array inteiro 4X2 e imprime seus atributos

O elemento deve ser um tipo de int16. Imprima os seguintes atributos:

*   A forma do array.
*   Dimensões do array
*   O comprimento de cada elemento do array em bytes.



Printing numpy array Attributes
1> Array Shape is:  (4, 2)
2>. Array dimensions are  2
3>. Length of each element of array in bytes is  2


In [30]:
import numpy as np

a = np.arange(8, dtype = np.int16).reshape((4, 2))
shape = np.shape(a)
dim = a.ndim
leng = a.itemsize

print("Array Shape is:",shape)
print("Array dimensions are", dim)
print("Length of each element of array in bytes is", leng)

Array Shape is: (4, 2)
Array dimensions are 2
Length of each element of array in bytes is 2


2) Crie um array de inteiros 5X2 de um intervalo entre 100 e 200, de modo que a diferença entre cada elemento seja 10 

Creating 5X2 array using numpy.arange
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [37]:
import numpy as np

a = np.arange(100, 200, 10).reshape((5, 2))

print("Creating 5X2 array using numpy.arange")
print(a)

Creating 5X2 array using numpy.arange
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


3) A seguir está um array numPy. Retorna o array de itens na terceira coluna de todas as linhas.

```
sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
```


Printing Input Array
[[11 22 33]
 [44 55 66]
 [77 88 99]]

 Printing array of items in the third column from all rows
[22 55 88]


In [72]:
import numpy as np 
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

print("Printing Input Array")
print(sampleArray)

print("\nPrinting array of items in the third column from all rows")
print(sampleArray[:,1])

Printing Input Array
[[11 22 33]
 [44 55 66]
 [77 88 99]]

Printing array of items in the third column from all rows
[22 55 88]


4) Retorna o array de linhas ímpares e colunas pares do numpy array abaixo:


```
sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
```



Printing Input Array
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

 Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]


In [137]:
import numpy as np 
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

print("Printing Input Array")
print(sampleArray)


print("\nPrinting array of odd rows and even columns")
print(sampleArray[::2, 1::2])


Printing Input Array
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]


5) Crie um array de resultado adicionando os dois numpy arrays. Em seguida, modifique o array de resultados calculando o quadrado de cada elemento.


```
arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])
```


addition of two arrays is 

[[20 39 33]
 [25 25 28]]

Result array after calculating the square root of all elements

[[ 400 1521 1089]
 [ 625  625  784]]


In [1]:
import numpy as np 
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
sumArray = arrayOne + arrayTwo
squareArray = np.square(sumArray)
print("addition of two arrays is\n", sumArray)

print("\nResult array after calculating the square root of all elements\n \n",squareArray)

addition of two arrays is
 [[20 39 33]
 [25 25 28]]

Result array after calculating the square root of all elements
 
 [[ 400 1521 1089]
 [ 625  625  784]]


6) Divida o array em quatro subarrays de tamanhos iguais. Crie um array de inteiros 8X3 deintervalo entre 10 a 34 de forma que a diferença entre cada elemento seja 1 e, em seguida, divida o array em quatro submatrizes de tamanhos iguais.


Creating 8X3 array using numpy.arange
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8X3 array into 4 sub array

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


In [1]:
import numpy as np

a = np.arange(10,34, 1).reshape((8, 3))
print("Creating 8X3 array using numpy.arange")
print(a)
print("\nDividing 8X3 array into 4 sub array\n")
b = np.split(a,4)
print(b)

Creating 8X3 array using numpy.arange
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8X3 array into 4 sub array

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


7) Ordene o seguinte array Numpy


1.   Ordene o array pela segunda linha
2.   Ordene o array pela segunda coluna



```
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
```






Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Sorting Original array by secoond row
[[73 43 34]
 [12 22 82]
 [66 94 53]]
Sorting Original array by secoond column
[[82 22 12]
 [34 43 73]
 [53 94 66]]


In [61]:
import numpy as np 
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print("Printing Original array\n", sampleArray)
print("Printing Original array\n", sampleArray[:,sampleArray[1,:].argsort()])
print("Sorting Original array by secoond column\n", sampleArray[sampleArray[:,1].argsort()])


Printing Original array
 [[34 43 73]
 [82 22 12]
 [53 94 66]]
Printing Original array
 [[73 43 34]
 [12 22 82]
 [66 94 53]]
Sorting Original array by secoond column
 [[82 22 12]
 [34 43 73]
 [53 94 66]]


8) Imprima o máximo do eixo 0 e mínimo do eixo 1 do seguinte array 2-D.


```
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
```


Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Printing amin Of Axis 1
[34 12 53]
Printing amax Of Axis 0
[82 94 73]


In [60]:
import numpy
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
print("Printing Original array\n", sampleArray)
a = numpy.amin(sampleArray, axis = 1)
b = numpy.amax(sampleArray, axis = 0)
print("Printing amin Of Axis 1\n", a)
print("Printing amax Of Axis 0\n", b)

Printing Original array
 [[34 43 73]
 [82 22 12]
 [53 94 66]]
Printing amin Of Axis 1
 [34 12 53]
Printing amax Of Axis 0
 [82 94 73]


9) Exclua a segunda coluna de um determinado array e insira a nova coluna seguinte em seu lugar.

```
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = numpy.array([[10,10,10]])

```

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


In [58]:
import numpy

sampleArray = numpy.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
newColumn = numpy.array([[10, 10, 10]])
print("Printing Original array\n", sampleArray)
sampleArray = numpy.delete(sampleArray, 2, axis=1)
print("Array after deleting column 2 on axis 1\n", sampleArray)
sampleArray = numpy.insert(sampleArray, 1, newColumn, axis=1)
print("Array after inserting column 2 on axis 1\n", sampleArray)

Printing Original array
 [[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
 [[34 43]
 [82 22]
 [53 94]]
Array after inserting column 2 on axis 1
 [[34 10 43]
 [82 10 22]
 [53 10 94]]
