1) Crie um Numpy array de acordo com lista abaixo e imprima-o. 


```
[1, 2, 3, 4]
```





In [5]:
import numpy as np
out = np.array([1, 2, 3, 4])
print(out)

[1 2 3 4]


2) Imprima o dtype do array.


```
v = np.array([1,2,3,4])
```



In [5]:
import numpy as np
v = np.array([1,2,3,4])
print(v.dtype)

int32


3) Crie o Numpy Array com os mesmos valores da questão anterior especificando o parâmetro dtype. Imprima o dtype do array criado.



```
 dtype='float64'
```




In [16]:
import numpy as np
v = np.array([1,2,3,4], dtype='float64')
print(v.dtype)

float64


4) Imprima o shape do array:

```
v = np.array([1.0,2.0,3.0,4.0])
```



In [18]:
import numpy as np

v = np.array([1.0,2.0,3.0,4.0])
print(v.shape)

(4,)


5) Realize um reshape em v para (2,2)

```
v = np.array([1.0,2.0,3.0,4.0])
```



In [19]:
import numpy as np
v = np.array([1.0,2.0,3.0,4.0])
v = v.reshape(2,2)
print(v)

[[1. 2.]
 [3. 4.]]


6) Crie arrays de zeros(3,3), ones(4,4) e um array diagonal(10,10) com valores 10 na diagonal, utilizando as funções 

```
zeros
ones
diag
```



In [57]:
import numpy as np
a = np.zeros((3, 3))

b = np.ones((4,4))

c = np.diag((10,10,10,10, 10,10, 10,10, 10,10))

print(a)
print(b)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[10  0  0  0  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  0  0]
 [ 0  0 10  0  0  0  0  0  0  0]
 [ 0  0  0 10  0  0  0  0  0  0]
 [ 0  0  0  0 10  0  0  0  0  0]
 [ 0  0  0  0  0 10  0  0  0  0]
 [ 0  0  0  0  0  0 10  0  0  0]
 [ 0  0  0  0  0  0  0 10  0  0]
 [ 0  0  0  0  0  0  0  0 10  0]
 [ 0  0  0  0  0  0  0  0  0 10]]


7) Crie duas sequências de arrays v e u utilizando o arange e outra linspace
paramentros para arange = (0,5,0.5)
paramentros para linspace = (0,5,10)


In [61]:
import numpy as np

v = np.arange(0,5,0.5)
u = np.linspace(0,5,10)
print(v)
print(u)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


8) Obtenha a média, menor valor e maior valor do array seguinte:


```
x = np.arange(10)
```



In [66]:
import numpy as np

x = np.arange(10)
media = np.mean(x)
maior = np.amax(x)
menor = np.min(x)
print("Média =", media)
print("Menor valor =",menor)
print("Arg max =", maior)


Média = 4.5
Menor valor = 0
Arg max = 9


9) Utilize a função 'dot' para realizar o produto interno entre os vetores u e v:


```
v = np.array([10,20,30])
u = np.array([2,2,2])
```



In [72]:
import numpy as np

v = np.array([10,20,30])
u = np.array([2,2,2])

w = np.dot(v,u)
print("w =", w)

w = 120


10) Crie uma matriz identidade de ordem 5 utilizando a função 'eye':


In [68]:
import numpy as np

matriz = np.eye(5,5)
print(matriz)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


11) Realize a multiplicação das matrizes:


```
v = np.array([10, 10])
A = np.arange(4).reshape(2,2)
```



In [88]:
import numpy as np

v = np.array([10, 10])
A = np.arange(4).reshape(2,2)
w = np.dot(A,v) #produto interno

# print(np.multiply(v,A)) método real de mult de matriz
print(w)

[10 50]


12) Faça a transposição da matriz A utilizando a função 'transpose':


```
A = np.arange(4).reshape(2,2)
```



In [90]:
import numpy as np

A = np.arange(4).reshape(2,2)
At = np.transpose(A)
print("Matriz A = \n", A)
print("Transposta de A = \n", At)


Matriz A = 
 [[0 1]
 [2 3]]
Transposta de A = 
 [[0 2]
 [1 3]]


13) Gere uma sequência de números pseudo aleatório do tamanho (4,4) utilizando o submódulo do numpy random.


```
import numpy.random as rd
```



In [93]:
import numpy.random as rd
print(rd.rand(4,4))

[[0.38789245 0.59313129 0.06404196 0.53125151]
 [0.74876758 0.03731827 0.76054571 0.59963604]
 [0.623179   0.88262473 0.50211657 0.86119492]
 [0.21733913 0.48187663 0.41359591 0.29350795]]


14) utilizando a função 'normal' do submódulo, crie uma sequência (4,40 que siga uma distribuição normal com desvio padrão = 1 e média = 10

In [100]:
import numpy.random as rd
print(rd.normal(10,1,[4,4])) # media , desvio, tamanho

[[10.28131633  8.98574815  8.60557767  8.75784654]
 [ 9.51668188  8.93138297  9.93421749 10.08047289]
 [ 9.9136548   9.22853823 13.16726121  9.65349629]
 [11.03128359 11.24321344 10.93793907  9.44021442]]


15) Utilize a função 'seed' para definir a semente do número pseudo aleatório a Utilize seed = 1000. A definição da semente deve ser feita antes de invocar a função 'rand'. Teste o valor de v1, execute mais de uma vez e veja o resultado:

```
v1 = rd.rand(4)
```



In [109]:
import numpy.random as rd
rd.seed(1000)
v1 = rd.rand(4)
print(v1)

[0.65358959 0.11500694 0.95028286 0.4821914 ]


16) Utilize a função 'inv' que pertence a submódulo 'linalg' para computar a matriz inversa de A.


```
A = np.array([10, 20, 30, 40]).reshape(2,2)
```


In [110]:
import numpy as np

A = np.array([10, 20, 30, 40]).reshape(2,2)
print(np.linalg.inv(A))

[[-0.2   0.1 ]
 [ 0.15 -0.05]]


17) Utilize a função 'det' que pertecene ao submódulo 'linalg' para calcular o determinante da matriz A.

```
A = np.array([10, 20, 30, 40]).reshape(2,2)
```

In [112]:
import numpy as np

A = np.array([10, 20, 30, 40]).reshape(2,2)
dA = np.linalg.det(A)
print("Determinante de A = %.2f" %dA)

Determinante de A = -200.00
